var countries = {
                 "images/maps/afghanistan.png": 
                     ["images/flags/af-lgflag.gif",
                      "images/religions/islam.jpg",
                      "images/income/2k.jpg",
                      "images/titles/afghanistan_title.jpg",],
                 "images/maps/albania.png": 
                     ["images/flags/al-lgflag.gif",
                      "images/religions/islam.jpg",
                      "images/income/10k.jpg",
                      "images/titles/albania_title.jpg",],
                 "images/maps/algeria.svg": 
                     ["images/flags/ag-lgflag.gif",
                      "images/religions/islam.jpg",
                      "images/income/15k.jpg",
                      "images/titles/algeria_title.jpg",],
                 "images/maps/angola.png": 
                     ["images/flags/ao-lgflag.gif",
                      "images/religions/christianity.jpg",
                      "images/income/8k.jpg",
                      "images/titles/angola_title.jpg",],
                 "images/maps/argentina.png": 
                     ["images/flags/ar-lgflag.gif",
                      "images/religions/christianity.jpg",
                      "images/income/20k.jpg",
                      "images/titles/argentina_title.jpg",],
                      /*
                 "images/maps/armenia.jpg": 
                     ["images/flags/am-lgflag.gif",
                      "images/religions/christianity.jpg",
                      "images/income/8k.jpg",
                      "images/titles/armenia_title.jpg",],
                      */
                 "images/maps/bangladesh.png": 
                     ["images/flags/bg-lgflag.gif",
                      "images/religions/islam.jpg",
                      "images/income/3k.jpg",
                      "images/titles/bangladesh_title.jpg",],
                 "images/maps/brazil.png": 
                     ["images/flags/br-lgflag.gif",
                      "images/religions/christianity.jpg",
                      "images/income/15k.jpg",
                      "images/titles/brazil_title.jpg",],
                      /*
                 "images/maps/burkina_faso.jpg": 
                     ["images/flags/uv-lgflag.gif",
                      "images/religions/islam.jpg",
                      "images/income/2k.jpg",
                      "images/titles/burkina_faso_title.jpg",],
                      */
                 "images/maps/canada.png": 
                     ["images/flags/ca-lgflag.gif",
                      "images/religions/christianity.jpg",
                      "images/income/45k.jpg",
                      "images/titles/canada_title.jpg",],
                 "images/maps/chile.png":
                     ["images/flags/ci-lgflag.gif", 
                      "images/religions/christianity.jpg",
                      "images/income/25k.jpg",
                      "images/titles/chile_title.jpg",], 
                 "images/maps/china.png":
                     ["images/flags/ch-lgflag.gif", 
                      "images/religions/nonreligious.jpg",
                      "images/income/15k.jpg",
                      "images/titles/china_title.jpg",], 
                 "images/maps/egypt.png":
                     ["images/flags/eg-lgflag.gif",
                      "images/religions/islam.jpg",
                      "images/income/10k.jpg",
                      "images/titles/egypt_title.jpg",],
                      /*
                 "images/maps/ethiopia.jpg":
                     ["images/flags/et-lgflag.gif",
                      "images/religions/christianity.jpg",
                      "images/income/2k.jpg",
                      "images/titles/ethiopia_title.jpg",],
                      */
                 "images/maps/france.png":
                     ["images/flags/fr-lgflag.gif",
                      "images/religions/christianity.jpg",
                      "images/income/40k.jpg",
                      "images/titles/france_title.jpg",],
                 "images/maps/germany.png":
                     ["images/flags/gm-lgflag.gif",
                      "images/religions/christianity.jpg",
                      "images/income/45k.jpg",
                      "images/titles/germany_title.jpg",],
                 "images/maps/india.png": 
                     ["images/flags/in-lgflag.gif", 
                      "images/religions/hinduism.jpg",
                      "images/income/6k.jpg",
                      "images/titles/india_title.jpg",], 
                 "images/maps/italy.png": 
                     ["images/flags/it-lgflag.gif", 
                      "images/religions/christianity.jpg",
                      "images/income/35k.jpg",
                      "images/titles/italy_title.jpg",], 
                 "images/maps/iran.png": 
                     ["images/flags/ir-lgflag.gif", 
                      "images/religions/islam.jpg",
                      "images/income/15k.jpg",
                      "images/titles/iran_title.jpg",], 
                 "images/maps/indonesia.png": 
                     ["images/flags/id-lgflag.gif", 
                      "images/religions/islam.jpg",
                      "images/income/10k.jpg",
                      "images/titles/indonesia_title.jpg",],
                 "images/maps/japan.png": 
                     ["images/flags/ja-lgflag.gif", 
                      "images/religions/nonreligious.jpg",
                      "images/income/40k.jpg",
                      "images/titles/japan_title.jpg",],
                      /*
                 "images/maps/mauritania.jpg":
                     ["images/flags/mr-lgflag.gif", 
                      "images/religions/islam.jpg",
                      "images/income/4k.jpg",
                      "images/titles/mauritania_title.jpg",], 
                      */
                 "images/maps/mexico.png": 
                     ["images/flags/mx-lgflag.gif",
                      "images/religions/christianity.jpg",
                      "images/income/20k.jpg",
                      "images/titles/mexico_title.jpg",],
                 "images/maps/nigeria.png": 
                     ["images/flags/ni-lgflag.gif",
                      "images/religions/christianity.jpg",
                      "images/income/6k.jpg",
                      "images/titles/nigeria_title.jpg",],
                 "images/maps/pakistan.png":
                     ["images/flags/pk-lgflag.gif", 
                      "images/religions/islam.jpg",
                      "images/income/5k.jpg",
                      "images/titles/pakistan_title.jpg",], 
                 "images/maps/philippines.png":
                     ["images/flags/rp-lgflag.gif", 
                      "images/religions/christianity.jpg",
                      "images/income/8k.jpg",
                      "images/titles/philippines_title.jpg",], 
                      /*
                 "images/maps/poland.jpg": 
                     ["images/flags/pl-lgflag.gif",
                      "images/religions/christianity.jpg",
                      "images/income/25k.jpg",
                      "images/titles/poland_title.jpg",],
                      */
                 "images/maps/russia.png":
                     ["images/flags/rs-lgflag.gif", 
                      "images/religions/christianity.jpg",
                      "images/income/25k.jpg",
                      "images/titles/russia_title.jpg",], 
                      /*
                 "images/maps/singapore.png":
                     ["images/flags/sn-lgflag.gif",
                      "images/religions/buddhism.jpg",
                      "images/income/80k.jpg",
                      "images/titles/singapore_title.jpg",],
                      */
                 "images/maps/south_africa.svg":
                     ["images/flags/sf-lgflag.gif",
                      "images/religions/christianity.jpg",
                      "images/income/15k.jpg",
                      "images/titles/south_africa_title.jpg",],
                 "images/maps/south_korea.png":
                     ["images/flags/ks-lgflag.gif",
                      "images/religions/nonreligious.jpg",
                      "images/income/35k.jpg",
                      "images/titles/south_korea_title.jpg",],
                 "images/maps/south_sudan.svg":
                     ["images/flags/od-lgflag.gif",
                      "images/religions/christianity.jpg",
                      "images/income/2k.jpg",
                      "images/titles/south_sudan_title.jpg",],
                 "images/maps/turkey.png": 
                     ["images/flags/tu-lgflag.gif", 
                      "images/religions/islam.jpg",
                      "images/income/20k.jpg",
                      "images/titles/turkey_title.jpg",], 
                 "images/maps/thailand.png": 
                     ["images/flags/th-lgflag.gif", 
                      "images/religions/buddhism.jpg",
                      "images/income/15k.jpg",
                      "images/titles/thailand_title.jpg",], 
                      /*
                 "images/maps/timor-leste.jpg": 
                     ["images/flags/tt-lgflag.gif", 
                      "images/religions/christianity.jpg",
                      "images/income/6k.jpg",
                      "images/titles/timor_leste_title.jpg",], 
                 "images/maps/united_arab_emirates.jpg": 
                     ["images/flags/ae-lgflag.gif",
                      "images/religions/islam.jpg",
                      "images/income/65k.jpg",
                      "images/titles/united_arab_emirates_title.jpg",],
                      */
                 "images/maps/united_kingdom.svg": 
                     ["images/flags/uk-lgflag.gif", 
                      "images/religions/christianity.jpg",
                      "images/income/40k.jpg",
                      "images/titles/united_kingdom_title.jpg",],
                 "images/maps/united_states.png": 
                     ["images/flags/us-lgflag.gif", 
                      "images/religions/christianity.jpg",
                      "images/income/55k.jpg",
                      "images/titles/united_states_title.jpg",],
                      /*
                 "images/maps/vietnam.png": 
                     ["images/flags/vm-lgflag.gif",
                      "images/income/6k.jpg",
                      "images/titles/vietnam_title.jpg",],
                      */
                }
